version: '3'
services:
  gopeed:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9999"
    volumes:
      - "${DOWNLOAD_PATH}:/root/Downloads"
    image: liwei2633/gopeed:v1.3.13@sha256:c73524840531d5f20620d6b2bc1c25386e1d9c0f3664d4452dd8bd010d8ce122
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
