version: '3'
services:
  gopeed:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9999"
    volumes:
      - "${DOWNLOAD_PATH}:/root/Downloads"
    image: liwei2633/gopeed:v1.3.12@sha256:914ae233cc3f093242b1a319c2dc2778af96b2cf57af468ee36165905896e287
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
