version: '3.8'
services:
  pingvin-share:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - "${DATA_PATH}:/opt/app/backend/data"
      - "${UPLOAD_PATH}:/opt/app/frontend/public/img"
    image: stonith404/pingvin-share:v0.18.1@sha256:af60d7873ce62009c6d74126693a392c60e2474b93317ea6acf8c7f8c6ce7658
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
