version: '3'
services:
  rss-reader:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}/db:/app/db"
      - "./data/config.json:/app/config.json"
    image: srcrs/rss-reader:v1.5@sha256:7594945c526ea9ae62799ee84de25e43914a4b9591a1bed225bde5f788910365
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
