version: '3.8'
services:
  pingvin-share:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - "${DATA_PATH}:/opt/app/backend/data"
      - "${UPLOAD_PATH}:/opt/app/frontend/public/img"
    image: stonith404/pingvin-share:v0.19.2@sha256:4196139988152a89f8158124798ba06a9552db73e544c7d0bc2b1d213e5c0e5d
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
